config/routes.rb
Rails.application.routes.draw do
  patch 'users/:id', to: 'users#user_update'
  devise_for :users
  root to: "pages#home"
  get "/home", to: "pages#home", as: :home
  get "/profiles", to: "pages#profiles"
  get "/emergency", to: "pages#emergency"
  get '/itineraries', to: 'itineraries#index', as: :itineraries

  post '/status_update', to: 'itineraries#status_update'


  resources :itineraries do
    resources :reviews
    resources :it_activities, only: %i[new index create destroy edit update]
  end

  resources :cities do
    resources :activities, only: %i[edit new]
  end

  resources :activities, only: %i[new create edit update destroy index]
  resources :users, only: %i[show edit update] do
    resources :messages, only: %i[index create]
    resources :chatrooms, only: %i[index show create]
  end
  resources :chatrooms, only: %i[index show edit update] do
    resources :messages, only: :create
  end
  # mount ActionCable.server => '/cable'
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :user
  belongs_to :city
  has_many :it_activities, dependent: :destroy
  validates :title, :start_date, :end_date, presence: true
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  # before_action :set_city, only: %i[update]
  before_action :set_itinerary, only: [:edit, :update, :show]
  skip_forgery_protection


  def index
    @itineraries = Itinerary.all
    @ongoing_itineraries = current_user.itineraries.where("start_date <= ? AND end_date >= ?", Date.today, Date.today)
    @upcoming_itineraries = current_user.itineraries.where("start_date > ? AND end_date >= ?", Date.today, Date.today)
    @past_itineraries = current_user.itineraries.where("end_date < ?", Date.today)
  end

  def status_update
    @itinerary = Itinerary.find(params[:id])
    @itinerary.status = true
    @itinerary.save!
  end

  def show
    @activities = Activity.where(city_id: @itinerary.city_id)
    @itactivity = ItActivity.new
    @itactivities = ItActivity.where(itinerary_id: @itinerary.id)
    @city = @itinerary.city
    @cities = City.all
    @markers = @itactivities.map do |itactivity|
      {
        lat: itactivity.activity.latitude,
        lng: itactivity.activity.longitude
      }
    end

    @marker = [lat: @city.latitude, lng: @city.longitude]
  end

  def new
    @itinerary = Itinerary.new
    @cities = City.all
  end

  def create
    start_date = params[:itinerary][:start_date].split(" to ")[0]
    end_date = params[:itinerary][:start_date].split(" to ")[1]
    @itinerary = Itinerary.new(start_date: start_date, end_date: end_date, **itinerary_params)
    @itinerary.user = current_user
    if @itinerary.save!
      redirect_to @itinerary
    else
      render :new
    end
  end

  def edit
    @city = @itinerary.city
    @itinerary.user = current_user
  end

  def update
    if @itinerary.update(itinerary_params)
      redirect_to itinerary_path(@itinerary)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @itinerary = Itinerary.find(params[:id])
    @itinerary.destroy
    redirect_to itineraries_url
  end


  private

  def set_itinerary
    @itinerary = Itinerary.find(params[:id])
  end

  def set_city
    @city = City.find(params[:city_id])
  end

  def itinerary_params
    if params[:itinerary][:start_date].present?
      start_date = params[:itinerary][:start_date].split(" to ")[0]
      end_date = params[:itinerary][:start_date].split(" to ")[1]
      params[:itinerary][:start_date] = start_date
      params[:itinerary][:end_date] = end_date
      params.require(:itinerary).permit(:user_id, :city_id, :title, :visibility, :status, :review, :start_date, :end_date)
    else
      params.require(:itinerary).permit(:user_id, :city_id, :title, :visibility, :status, :review)
    end
  end
end

app/views/itineraries/_new.html.erb
<h2>New itinerary</h2>

  <div class="row col-10 justify-content-center newpage">
      <%= simple_form_for @itinerary do |f| %>
      <%= f.input :title %>
      <%= f.input :city_id, collection: @cities, label_method: :name, value_method: :id, prompt: true %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.input :visibility %>
      <%= f.submit class: "btn btn-warning" %>
    <% end %>
  </div>

app/views/itineraries/edit.html.erb
<div class="header d-flex justify-content-between p-3 mb-3" style="height:60px;">
  <%= link_to itineraries_path, class: 'add-button' do %>
    <h4><i class="fa-solid fa-chevron-left" style="color:white;"></i></h4>
  <% end %>
  <h4>Edit trip to <%= @itinerary.city.name %></h4>
</div>

<div class="container itin-index" style="width:90%; margin-bottom:100px;">

    <%= simple_form_for @itinerary do |f| %>
    <div class="form-inputs">
      <%= link_to itinerary_path(@itinerary) do %>

      <div class="card-category-img mb-3" style="background-image:url(<%= @itinerary.city.image_url_one %>); width:100%; height:200px; padding:10px; background-size: cover;"></div>
      <% end %>
      <%= f.input :title %>
      <% if @itinerary.end_date.past? %>
        <%= f.input :review, as: :text %>
      <% end %>
      <% unless @itinerary.end_date.past? %>
        <%= f.input :start_date, as: :string, label: "Change your dates",
                    input_html: { data: { controller: "datepicker" } } %>
      <% else %>
        <p><%= @itinerary.start_date %> to <%= @itinerary.end_date %></p>
      <% end %>
      <%= f.input :visibility, as: :boolean %>
        <div class="form-actions">
        <%= f.button :submit, "Update" %>
      </div>
    <% end %>
</div>
</div>

app/views/itineraries/index.html.erb
<div class="header d-flex justify-content-between p-3 mb-3" style="height:60px;">
  <h4>Trips</h4>
  <%= link_to new_itinerary_path, class: 'add-button' do %>
    <h4><i class="fa-solid fa-circle-plus" style="color:white;"></i></h4>
  <% end %>
</div>

<div class="container itin-index" style="width:60%; margin-bottom:100px;">

  <% @ongoing_itineraries.group_by(&:city).each do |city, itineraries| %>
  <a href="<%= itinerary_path(itineraries.first) %>" style="text-decoration:none;">
    <div style="position:relative;">
      <div class="card-category-img mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= city.image_url_one %>); width:100%; height:200px; padding:10px; background-size: cover;">
        <div class="d-flex flex-column mt-2" style="text-align:center">
          <h2><%= city.name %></h2>
            <% itineraries.each do |itinerary| %>
            <p style="font-size:12px; font-weight: 200;"><%= itinerary.start_date.strftime('%B %d ') %> - <%= itinerary.end_date.strftime('%B %d ') %></p>
          <% end %>
        </div>
      </div>
    </a>
  <% end %>
  <div>
  <div class="master">
    <span><strong>Upcoming Trips</strong></span>
      <%= render "layouts/upcoming_itinerary_activity_card" %>
    <div class="accordion mt-3" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <strong>Past Trips</strong>
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <%= render "layouts/past_itinerary_activity_card" %>
          </div>
        </div>
      </div>

    </div>
  </div>
  </div>

  </div>
</div>

app/views/itineraries/new.html.erb
<div class="header d-flex justify-content-between p-3 mb-3" style="height:60px;">
  <%= link_to itineraries_path, class: 'add-button' do %>
    <h4><i class="fa-solid fa-chevron-left" style="color:white;"></i></h4>
  <% end %>
  <h4>New trip</h4>
</div>

<div class="container itin-index" style="width:90%; margin-bottom:100px;">

      <div class="form-inputs">
        <%= simple_form_for @itinerary do |f| %>
        <%= f.input :title %>
        <%= f.input :city_id, collection: @cities, label_method: :name, value_method: :id, prompt: true %>
        <%= f.input :start_date, as: :string, label: "Pick your dates",
              input_html: { data: { controller: "datepicker" } } %>
        <%= f.input :visibility %>
      <div class="form-actions">
        <%= f.button :submit, "Create" %>
      </div>
      <% end %>
    </div>
</div>

app/views/itineraries/show.html.erb
<div class="header col-12 d-flex justify-content-between p-3" style="height:60px;">
  <%= link_to itineraries_path, class: 'add-button' do %>
    <h4><i class="fa-solid fa-chevron-left" style="color:white;"></i></h4>
  <% end %>

  <h5>
  <% if !@itinerary.end_date.past? %>
      <%= @city.name %>
      <%= link_to icon('fa-regular', 'edit icon-hover-edit'), edit_itinerary_path(@itinerary) %>
    <% else %>
      <%= @city.name %>
    <% end %>
  </h5>

  <div>
    <h4><%= link_to city_path(@itinerary.city) do %><i class="fas fa-search"></i><% end %></h4>
  </div>

</div>

<div class="container itin-index" style="width:60%; margin-bottom:100px;">

<div style="text-align:center; margin-top:20px; margin-bottom:20px;">
  <h4>
    <%= @itinerary.title %>
    <% if !@itinerary.end_date.past? %>
    <span data-controller="email" data-email-id-value="<%= @itinerary.id%>" style="font-size:20px;">
      <a href="#"data-action="click->email#show"><i class="fa fa-paper-plane" style="color:#524FF7;"></i></a>
    </span>
    <% end %>
  </h4>
  <p><%= @itinerary.start_date.strftime('%B %d ') %> - <%= @itinerary.end_date.strftime('%B %d ') %> </p>
</div>

<%= render "layouts/map" %>


<div style="margin-top:20px; margin-bottom:20px;"><h6><% if !@itinerary.end_date.past? %><%= link_to new_city_activity_path(@itinerary.city_id, itinerary_id: @itinerary.id, custom: true ), style:"text-decoration:none;" do %> <span style="color:black;">Add an Activity</span>     <i class="fas fa-plus-circle" style="color:#524FF7;"></i><% end %><% end %></h6></div>


<% sorted_it_activities = @itinerary.it_activities.includes(:activity).order(:date).group_by(&:date) %>
<% sorted_it_activities.keys.each do |date| %>
  <% if date.present? %>
    <p><%= date.strftime('%A, %B %d') %></p>
  <% else %>
    <p></p>
  <% end %>
  <% sorted_it_activities[date].each do |it_activity| %>
    <div class="card-product">
      <% activity = it_activity.activity %>
      <% if activity.image_url.present? %>
        <img src="<%= activity.image_url %>" alt="">
      <% else %>
        <img src="https://a.storyblok.com/f/112937/568x464/884e373bca/travel_pic_unsplash1-568x464.jpg/m/620x0/filters:quality(70)/" alt="">
      <% end %>
      <div class="card-product-infos" data-controller="toggler">
        <h2 data-action="click->toggler#toggle"><%= activity.title %></h2>
          <% if activity.custom? %>
              <div data-toggler-target="togglableElement" class="d-none">
                <%= form_with(model: activity, url: activity_path(activity), class: 'hidden-form', local: true) do |form| %>
                  <%= form.text_field :title, value: activity.title %>
                  <%= form.text_field :address, value: activity.address %>
                  <%= form.submit 'Update', class: 'update-button' %>
                <% end %>
              </div>
          <% end %>
        <h2 class="d-flex" style="color:#524FF7;">
          <div data-controller="calendar">
              <div class="delete">
                  <%= link_to icon('fa-regular', 'circle-xmark'), itinerary_it_activity_path(@itinerary, it_activity), data: { turbo_method: :delete } %>
              </div>
              <div data-calendar-target="togglableElement" class="d-none">
                <%= form_with(model: it_activity, url: itinerary_it_activity_path(@itinerary, it_activity), class: 'hidden-form', local: true) do |form| %>
                  <%= form.date_field :date %>
                  <%= form.submit 'Update', class: 'update-button' %>
                <% end %>
              </div>
          </div>
        </h2>
      </div>
    </div>
  <% end %>
<% end %>

<% if !@itinerary.end_date.past? %>
  <strong>Our Suggestions</strong>
<div class="scroll-container">
  <% @activities.each do |activity| %>
    <div class="activity-image-container" data-controller="toggler">
              <% unless activity.custom || @itinerary.it_activities.exists?(activity_id: activity.id) %>
                  <% if activity.image_url.present? %>
                    <img src="<%= activity.image_url %>" alt="" data-action="click->toggler#toggle">
                  <% end %>
                  <div data-toggler-target="togglableElement" class="d-none">
                    <div class="blue d-flex flex-column shadow-lg p-3 mb-1 bg-white">
                      <img src="<%= activity.image_url %>" style="width: 100%;height: 200px; object-fit: cover;border-radius:5px;">

                        <div>
                          <h2><% if activity.title.length > 20 %>
                            <%= "#{activity.title.slice(0,20)}..." %>
                            <% else %>
                            <%= activity.title %><% end %></h2>
                          <p>Pick a day:</p>
                          <%= simple_form_for([@itinerary, ItActivity.new]) do |f| %>
                            <%= f.hidden_field :activity_id, value: activity.id %>
                            <%= f.hidden_field :itinerary_id, value: @itinerary.id %>
                          <div class="d-flex justify-content-center">
                            <%= f.date_field :date, class:"form-actions", style: "border: 0;width: 12%;" %>
                            <%= f.button :submit, "+", class:"form-actions", style: "width: 12%;", disabled: @itinerary.it_activities.exists?(activity_id: activity.id) %>
                            <%= link_to 'x', itinerary_path(@itinerary), class:"form-actions", style: "width: 12%; text-decoration:none; color: black" %>
                          </div>
                          <% end %>
                      </div>
                    </div>
                  </div>
              <% end %>
            </div>
          <% end %>
      </div>
    <% else %>
      <% if @itinerary.review.present? %>
        <h5>Review</h5>
        <%= @itinerary.review %>
      <% end %>
    <% end %>
</div>

</div>