config/routes.rb
Rails.application.routes.draw do
  patch 'users/:id', to: 'users#user_update'
  devise_for :users
  root to: "pages#home"
  get "/home", to: "pages#home", as: :home
  get "/profiles", to: "pages#profiles"
  get "/emergency", to: "pages#emergency"
  get '/itineraries', to: 'itineraries#index', as: :itineraries

  post '/status_update', to: 'itineraries#status_update'


  resources :itineraries do
    resources :reviews
    resources :it_activities, only: %i[new index create destroy edit update]
  end

  resources :cities do
    resources :activities, only: %i[edit new]
  end

  resources :activities, only: %i[new create edit update destroy index]
  resources :users, only: %i[show edit update] do
    resources :messages, only: %i[index create]
    resources :chatrooms, only: %i[index show create]
  end
  resources :chatrooms, only: %i[index show edit update] do
    resources :messages, only: :create
  end
  # mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  # mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, presence: true

  has_one_attached :photo
  has_many :itineraries
  has_many :chatrooms_as_user1, class_name: 'Chatroom', foreign_key: 'user1', dependent: :destroy
  has_many :chatrooms_as_user2, class_name: 'Chatroom', foreign_key: 'user2', dependent: :destroy
  has_many :messages, dependent: :destroy

  def password_optional?
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @chatroom = Chatroom.where(user1: current_user, user2: @user).or(Chatroom.where(user1: @user, user2: current_user))
    @chatroom = @chatroom.empty? ? Chatroom.new : @chatroom.first
  end

  def create
    @user = User.new(user_params)
    @User.save!
  end

  def edit
    @user = User.find(params[:id])
    @user = current_user
  end

  def user_update
    @user = User.find(params[:id])
    if @user.update!(user_params)
      redirect_to user_path(@user)
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :summary, :emergency_contact_name, :emergency_contact_number, :photo)
  end
end

app/views/users/edit.html.erb
<div class="header d-flex justify-content-between p-3 mb-3" style="height:60px;">
  <%= link_to user_path, class: 'add-button' do %>
    <h4><i class="fa-solid fa-chevron-left" style="color:white;"></i>      Profile</h4>
  <% end %>
</div>


<div class="container itin-index" style="width:90%; margin-bottom:100px;">

<div class="profile-card">
  <div class="card-content">
    <%= cl_image_tag @user.photo.key %>
  </div>
  <div class="d-flex flex-column align-items-center">
    <h4 class="mt-2"><strong><%= @user.first_name %> <%= @user.last_name %></strong></h4>
  </div>
</div>

<div class="pt-3">
  <%= simple_form_for @user, html: { multipart: true }, method: :patch do |f| %>
    <div><%= f.input :first_name %></div>
    <div><%= f.input :photo, as: :file %></div> <!-- Add this line for the file input -->
    <div><%= f.input :summary, label: "Biography" %></div>
    <div><%= f.input :emergency_contact_name %></div>
    <div><%= f.input :emergency_contact_number %></div>
    <div class="form-actions">
      <%= f.button :submit, "Update" %>
    </div>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="header d-flex justify-content-between p-3 mb-3" style="height:60px;">
  <h4>Profile</h4>
</div>

<div class="container itin-index" style="width:90%; margin-bottom:100px;">

  <div class="profile-card">
    <div class="card-content">
      <%= cl_image_tag @user.photo.key %>
    </div>
    <div class="d-flex flex-column align-items-center">
      <h4 class="mt-2"><strong><%= @user.first_name %> <%= @user.last_name %></strong></h4>
      <% if user_signed_in? && current_user == @user %>
        <div><%= link_to edit_user_url do %><i class="fas fa-edit" style="color:#524FF7;"></i><% end %></div>
        <% else %>
        <div>
            <% chatroom = current_user.chatrooms_as_user1.where(user2: @user.id).first %>
        <% if !chatroom.present? %>
          <% chatroom = current_user.chatrooms_as_user2.where(user1: @user.id).first %>
        <% end %>
        <% if chatroom.present? %>
          <%= link_to icon('fa-solid', 'comment'), chatroom_path(@chatroom) %>
        <% else %>
          <%= link_to icon('fa-solid', 'comment'), user_chatrooms_path(current_user.id), data: {turbo_method: :post} %>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>

<div class="bio-user">
  <strong><p>Biography</p></strong>
  <p><%= @user.summary %></p>
</div>

<% if @user.itineraries.where(visibility: true).present? %>
<strong><p>Trips</p></strong>
<% end %>
<div class="scroll-container m-0">
  <% @user.itineraries.where(visibility: true).each do |itinerary| %>
    <div class="activity-image-container m-0" style="position: relative;">
      <%= link_to itinerary_path(itinerary) do %>
        <%= image_tag itinerary.city.image_url_one, style: "width:100%; height:100px; object-fit:contain; border-radius:10px;", alt: "" %>
      <% end %>
      <div class="image-overlay" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center; color: white; font-size: 16px; font-weight: bold;">
        <%= itinerary.city.name %>
      </div>
    </div>
  <% end %>
</div>

<div class="log-out">
  <%= button_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete, data: { turbo: false } %>
</div>
</div>