config/routes.rb
Rails.application.routes.draw do
  patch 'users/:id', to: 'users#user_update'
  devise_for :users
  root to: "pages#home"
  get "/home", to: "pages#home", as: :home
  get "/profiles", to: "pages#profiles"
  get "/emergency", to: "pages#emergency"
  get '/itineraries', to: 'itineraries#index', as: :itineraries

  post '/status_update', to: 'itineraries#status_update'


  resources :itineraries do
    resources :reviews
    resources :it_activities, only: %i[new index create destroy edit update]
  end

  resources :cities do
    resources :activities, only: %i[edit new]
  end

  resources :activities, only: %i[new create edit update destroy index]
  resources :users, only: %i[show edit update] do
    resources :messages, only: %i[index create]
    resources :chatrooms, only: %i[index show create]
  end
  resources :chatrooms, only: %i[index show edit update] do
    resources :messages, only: :create
  end
  # mount ActionCable.server => '/cable'
end

app/views/layouts/_calendar.html.erb
<div>
  <%= simple_form_for @itinerary  do |f| %>
    <%= f.input :start_date, as: :string, label: "Pick a date",
              input_html: { data: { controller: "datepicker" } } %>
  <% end %>
</div>

app/views/layouts/_card_activity.html.erb
<div class="category"></div>
<i class="fa-solid fa-earth-americas"></i> <strong>Culture</strong>
<div class="scroll-container">
  <% @culture_activities.each do |activity| %>
    <div class="activity-image-container">
      <div data-controller="toggler" data-action="click->toggler#toggle">
        <img src="<%= activity.image_url %>" alt="">
        <div data-toggler-target="togglableElement" class="d-none">
          <div class="yellow d-flex flex-column shadow-lg p-3 mb-5 bg-white">
            <img src="<%= activity.image_url %>" style="width: 100%;height: 180px; object-fit: cover; border-radius:5px;">
            <div class="d-flex justify-content-between">
              <div><h2> <% if activity.title.length > 25 %>
                <%= "#{activity.title.slice(0,25)}..." %>
              <% else %>
                <%= activity.title %><% end %></h2></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="category"></div>
<i class="fa-solid fa-tree"></i> <strong>Nature</strong>
<div class="scroll-container">
  <% @nature_activities.each do |activity| %>
    <div class="activity-image-container">
      <div data-controller="toggler" data-action="click->toggler#toggle">
        <img src="<%= activity.image_url %>" alt="">
        <div data-toggler-target="togglableElement" class="d-none">
          <div class="yellow d-flex flex-column shadow-lg p-3 mb-5 bg-white">
            <img src="<%= activity.image_url %>" style="width: 100%;height: 180px; object-fit: cover; border-radius:5px;">
            <div class="d-flex justify-content-between">
              <div><h2> <% if activity.title.length > 25 %>
                <%= "#{activity.title.slice(0,25)}..." %>
              <% else %>
                <%= activity.title %><% end %></h2></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="category"></div>
<i class="fa-solid fa-palette"></i> <strong>Art</strong>
<div class="scroll-container">
  <% @art_activities.each do |activity| %>
    <div class="activity-image-container">
      <div data-controller="toggler" data-action="click->toggler#toggle">
        <img src="<%= activity.image_url %>" alt="">
        <div data-toggler-target="togglableElement" class="d-none">
          <div class="yellow d-flex flex-column shadow-lg p-3 mb-5 bg-white">
            <img src="<%= activity.image_url %>" style="width: 100%;height: 180px; object-fit: cover; border-radius:5px;">
            <div class="d-flex justify-content-between">
              <div><h2> <% if activity.title.length > 25 %>
                <%= "#{activity.title.slice(0,25)}..." %>
              <% else %>
                <%= activity.title %><% end %></h2></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="category"></div>
<i class="fa-solid fa-utensils"></i> <strong>Food</strong>
<div class="scroll-container">
  <% @food_activities.each do |activity| %>
    <div class="activity-image-container">
      <div data-controller="toggler" data-action="click->toggler#toggle">
        <img src="<%= activity.image_url %>" alt="">
        <div data-toggler-target="togglableElement" class="d-none">
          <div class="yellow d-flex flex-column shadow-lg p-3 mb-5 bg-white">
            <img src="<%= activity.image_url %>" style="width: 100%;height: 180px; object-fit: cover; border-radius:5px;">
            <div class="d-flex justify-content-between">
              <div><h2> <% if activity.title.length > 25 %>
                <%= "#{activity.title.slice(0,25)}..." %>
              <% else %>
                <%= activity.title %><% end %></h2></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_card_carousel.html.erb
<% cities.each do |city| %>
  <div class="card-trip">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
      <a href="<%= city_path(city.id) %>">
        <img src="<%= city.image_url_one %>" class="d-block w-100" alt="...">
        </a>
      </div>
      <div class="carousel-item">
      <a href="<%= city_path(city.id) %>">
        <img src="<%= city.image_url_two %>" class="d-block w-100" alt="...">
      </a>
      </div>
      <div class="carousel-item">
      <a href="<%= city_path(city.id) %>">
        <img src="<%= city.image_url_three %>" class="d-block w-100" alt="...">
        </a>
      </div>
    </div>
  </div>
  <div class="card-trip-infos">
    <div>
      <h2><%= city.name%>, <%= city.country %></h2>
        <% if city.safety_rating == 1 %>
          <div class="safety-rating" style="background-color:#B7D480;">Safety Rating: <%= city.safety_rating %></div>
        <% elsif city.safety_rating == 2 %>
          <div class="safety-rating" style="background-color:#FDD984;">Safety Rating: <%= city.safety_rating %></div>
        <% elsif city.safety_rating == 3 %>
          <div class="safety-rating" style="background-color:#FFA676;">Safety Rating: <%= city.safety_rating %></div>
        <% else%>
          <div class="safety-rating" style="background-color:#F7574F;">Safety Rating: <%= city.safety_rating %></div>
        <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_itactivities.html.erb
<div class="header col-12 d-flex justify-content-between p-3" style="height:60px;">
  <%= link_to itineraries_path, class: 'add-button' do %>
    <h4><i class="fa-solid fa-chevron-left" style="color:white;"></i></h4>
  <% end %>
  <div><h5><%= @itinerary.title %>    <% if !@itinerary.end_date.past? %><%= link_to new_city_activity_path(@itinerary.city_id, itinerary_id: @itinerary.id, custom: true ) do %><i class="fas fa-plus-circle"><% end %></i><% end %></h5></div>
  <div>
    <h4><%= link_to city_path(@itinerary.city) do %><i class="fas fa-search"></i><% end %></h4>
  </div>
</div>

<%= render "layouts/map" %>

<% sorted_it_activities = @itinerary.it_activities.includes(:activity).order(:date).group_by(&:date) %>
<% sorted_it_activities.keys.each do |date| %>

  <% if date.present? %>
    <p><%= date.strftime('%A, %d %B') %></p>
  <% else %>
    <p>Unspecified Date</p>
  <% end %>


<div class="container m-2">

  <div><strong>PLAN ACTIVITIES</strong></div>

  <% sorted_it_activities[date].each do |it_activity| %>
      <div class="card-product">
        <% activity = it_activity.activity %>
        <% if activity.image_url.present? %>
          <img src="<%= activity.image_url %>" alt="">
        <% else %>
          <img src="https://www.rnd.de/resizer/y7y4Ajdp0erQTzUCdux_RnhnuWQ=/1441x1081/filters:quality(70)/cloudfront-eu-central-1.images.arcpublishing.com/madsack/KDRDXITX2NDY5NQOC34BSE3NNY.jpg" alt="">
        <% end %>
        <div class="card-product-infos">
          <h2><%= activity.title %></h2>
          <h2 class="d-flex"><%= link_to icon('fa-regular', 'edit icon-hover-edit'), itinerary_it_activity_path(@itinerary, it_activity) %>
              <%= link_to icon('fa-regular', 'trash-can icon-hover-trash'), itinerary_it_activity_path(@itinerary, it_activity), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this activity?" } %>
              <div data-controller="calendar">
                <i class="fa-regular fa-calendar" data-action="click->calendar#toggle"></i>
                <div data-calendar-target="togglableElement" class="d-none">
                  <%= form_with(model: it_activity, url: itinerary_it_activity_path(@itinerary, it_activity), class: 'hidden-form', local: true) do |form| %>
                    <%= form.date_field :date %>
                    <%= form.submit 'Update', class: 'update-button' %>
                  <% end %>
                </div>
              </div></h2>
        </div>
      </div>

      <% if activity.custom? %>
        <div data-controller="toggler">
          <i class="fa-regular fa-pen-to-square" data-action="click->toggler#toggle"></i>
          <div data-toggler-target="togglableElement" class="d-none">
            <%= form_with(model: activity, url: activity_path(activity), class: 'hidden-form', local: true) do |form| %>
              <%= form.text_field :title, value: activity.title %>
              <%= form.text_field :address, value: activity.address %>
              <%= form.submit 'Update', class: 'update-button' %>
            <% end %>
          </div>
        </div>
      <% end %>


      <% end %>
      </div>
    <% end %>

    <% if !@itinerary.end_date.past? %>
      <div class="category">
        <strong>Our top selection for you:</strong>
      </div>
      <div class="scroll-container">
          <% @activities.each do |activity| %>
            <div class="activity-image-container" data-controller="toggler">
              <% unless activity.custom || @itinerary.it_activities.exists?(activity_id: activity.id) %>
                  <% if activity.image_url.present? %>
                    <img src="<%= activity.image_url %>" alt="" data-action="click->toggler#toggle">
                  <% end %>
                  <%= activity.title %>
                  <div data-toggler-target="togglableElement" class="d-none">
                    <%= simple_form_for([@itinerary, ItActivity.new]) do |f| %>
                      <%= f.hidden_field :activity_id, value: activity.id %>
                      <%= f.hidden_field :itinerary_id, value: @itinerary.id %>
                      <%= f.date_field :date %>
                      <%= f.button :submit, "+", class: "btn btn-primary btn-sm", disabled: @itinerary.it_activities.exists?(activity_id: activity.id) %>
                    <% end %>
                    </div>
              <% end %>
            </div>
          <% end %>
      </div>
    <% else %>
      <% if @itinerary.review.present? %>
        <h5>Review</h5>
        <%= @itinerary.review %>
      <% end %>
    <% end %>
</div>

app/views/layouts/_loading_screen.html.erb
<div class="homewrapper">
  <div class="logoholder"></div>
  </div>

app/views/layouts/_map.html.erb
<% if @itactivities.empty? %>
  <div style="width: 100%; height: 200px;" id="city"
    data-controller="map"
    data-map-markers-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['pk.eyJ1Ijoic2ViaWJhc3RpIiwiYSI6ImNsaGhnMjZ0aDBiYnUzbXByeXUwOGtiYWYifQ.-eVD2Jk29XEU7OpQmFeMWQ'] %>">
  </div>
<% else %>
  <div style="width: 100%; height: 200px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['pk.eyJ1Ijoic2ViaWJhc3RpIiwiYSI6ImNsaGhnMjZ0aDBiYnUzbXByeXUwOGtiYWYifQ.-eVD2Jk29XEU7OpQmFeMWQ'] %>">
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="icons-container">
  <div class="icon-text-container <%= 'active' if request.path == root_path %>">
    <a href="/home">
      <div class="icon">
        <%# <i class="fa-solid fa-magnifying-glass"></i> %>
        <i class="fa-solid fa-magnifying-glass-location"></i>
      </div>
        <div class="text">
          Explore
        </div>
      </a>
      </div>

   <div class="icon-text-container <%= 'active' if request.path == itineraries_path %>">
      <a href="/itineraries">
        <div class="icon">
          <%# <i class="fa-regular fa-suitcase"></i> %>
          <i class="fa-solid fa-suitcase-rolling"></i>
        </div>
        <div class="text">
          Trip
        </div>
      </a>
      </div>

  <div class="icon-text-container <%= 'active' if request.path == emergency_path %>">
      <a href="/emergency">
        <div class="icon">
          <%# <i class="fa-regular fa-bell"></i> %>
          <i class="fa-solid fa-bell"></i>
        </div>
        <div class="text">
          Emergency
        </div>
      </a>
      </div>
  <div class="icon-text-container <%= 'active' if request.path == chatrooms_path %>">
        <a href="<%= chatrooms_path %>">
          <div class="icon">
            <i class="fa-solid fa-message"></i>
          </div>
          <div class="text">
            Chat
          </div>
        </a>
      </div>
  <div class="icon-text-container <%= 'active' if user_signed_in? && current_page?(user_path(current_user)) %>">
  <% if user_signed_in? %>
    <%= link_to user_path(current_user) do  %>
      <div class="icon">
        <%# <i class="fa-regular fa-user"></i> %>
        <i class="fa-solid fa-user"></i>
      </div>
      <div class="text">
        Profile
      </div>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do  %>
      <div class="icon">
        <%# <i class="fa-regular fa-user"></i> %>
        <i class="fa-solid fa-user"></i>
      </div>
      <div class="text">
        Profile
      </div>
    <% end %>
  <% end %>
</div>

</div>
</nav>

app/views/layouts/_ongoing_itinerary_activity_card.html.erb
<% @ongoing_itineraries.group_by(&:city).each do |city, itineraries| %>
<div class="card-product">
  <a href="<%= itinerary_path(itineraries.first) %>">
    <img src="<%= city.image_url_one %>" />
  </a>
  <div class="card-product-infos">
  <% itineraries.each do |itinerary| %>
    <h2>
      <%= itinerary.title %>
      <%= link_to icon('fa-regular', 'trash-can icon-hover-trash'), itinerary_path(itinerary), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this itinerary?" } %>
      <%= link_to icon('fa-regular', 'edit icon-hover-edit'), edit_itinerary_path(itinerary) %>
    </h2>
    <h2><%= city.name %></h2>
      <p><%= itinerary.start_date %> - <%= itinerary.end_date %><p>
  </div>
  <% end %>
  </div>
</div>
<% end %>

app/views/layouts/_past_itinerary_activity_card.html.erb
<% @past_itineraries.each do |itinerary| %>
  <div class="card-product">
    <a href="<%= itinerary_path(itinerary) %>">
      <img src="<%= itinerary.city.image_url_one %>" />
    </a>
    <div class="card-product-infos">
        <% unless itinerary.review.present? %>
          <%= link_to "Review your trip!", edit_itinerary_path(itinerary), class: 'edit-icon text-warning' %>
          <h2><%= itinerary.title %></h2>
        <% else %>
        <h2><%= itinerary.title %></h2>
        <% end %>
        <div class="delete">
        <%= link_to icon('fa-regular', 'circle-xmark'), itineraries_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this itinerary?" } %>
      </div>
      <h3><%= itinerary.city.name %></h3>
      <p><%= itinerary.start_date.strftime('%B %d, %Y') %> - <%= itinerary.end_date.strftime('%B %d, %Y') %></p>
    </div>
  </div>
<% end %>

app/views/layouts/_search_bar.html.erb
<div class="search">
  <%= form_with url: cities_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control ps-4",
      style: "border-radius: 20px; width: 1250px;",
      placeholder: "Browse cities..."
    %>
  <% end %>
</div>

app/views/layouts/_search_bar_home.html.erb
<div class="search">
<i class="fa-solid fa-magnifying-glass"></i>
  <%= form_with url: cities_path, method: :get, html: {class:
    "d-flex", data: {search_cities_target: "form"}} do |f| %>
    <%= f.text_field :query,
                     class: "form-control ps-4",
                     placeholder: "   Browse cities...",
                     style: "border-radius: 20px; width: 1250px;",
                     value: params[:query],
                     data: {search_cities_target: "input",
                     action: "keyup->search-cities#update",
                     } %>
  <% end %>
</div>


<%# <div class="search"> %>
<%# <i class="fa-solid fa-magnifying-glass"></i> %>
  <%# <%= form_with url: cities_path, method: :get, class: "d-flex" do %>
    <%# <%= text_field_tag :query, %>
      <%# params[:query], %>
      <%# class: "form-control ps-4", %>
      <%# style: "border-radius: 20px; width: 1250px;", %>
      <%# placeholder: "   Browse cities..." %>
    <%# %>
  <%# <% end %>
<%# </div> %>

app/views/layouts/_search_bar_index.html.erb
<div class="search">
<i class="fa-solid fa-magnifying-glass"></i>
  <%= form_with url: cities_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control ps-4",
      style: "border-radius: 20px; width: 1250px;",
      placeholder: "   Browse activities..."
    %>
  <% end %>
</div>

app/views/layouts/_suggestions_cards.html.erb
<% @activities.each do |activity| %>
<div class="card-trip">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item">
          <div class="activity-image-container">
            <% unless activity.custom || @itinerary.it_activities.exists?(activity_id: activity.id) %>
                <% if activity.image_url.present? %>
                  <img src="<%= activity.image_url %>" alt="">
                <% end %>
          </div>

          <div class="card-trip-infos">
            <%= activity.title %>
          </div>

      </div>
    </div>
            <% else %>
              <% if @itinerary.review.present? %>
      <div class="carousel-item">
                <h5>Review</h5>
                <%= @itinerary.review %>
      </div>
            <% end %>

        <% end %>
  </div>
</div>
<% end %>

app/views/layouts/_upcoming_itinerary_activity_card.html.erb
<% @upcoming_itineraries.group_by(&:city).each do |city, itineraries| %>
  <div class="card-product">
    <a href="<%= itinerary_path(itineraries.first) %>">
      <img src="<%= city.image_url_one %>"/>
    </a>

  <div class="card-product-infos">
  <% itineraries.each do |itinerary| %>
    <h2><%= itinerary.title %></h2>

    <h3><%= city.name %></h3>
      <p><%= itinerary.start_date.strftime('%B %d, %Y') %> - <%= itinerary.end_date.strftime('%B %d, %Y') %><p>
    <h2 class="delete">
      <%= link_to icon('fa-regular', 'circle-xmark'), itinerary_path(itinerary), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this itinerary?" } %>
    </h2>
      <% end %>
    </div>
  </div>
<% end %>